spring:
  application:
    name: mypage

  csrf:
    enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/mypage?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: bpea2641

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

openai:
  api-key: ${OPENAI_API_KEY}

jwt:
  secret: c9b0052b7481f8c89c8467a58651d87fbc4654c2c36e3a3f2b9f3f8b3e3f3b3a  # 중괄호 제거